name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore YourWpfApp/YourWpfApp.csproj

      - name: Build Solution
        run: dotnet build YourWpfApp/YourWpfApp.csproj -c Release

      - name: Run Unit Tests
        run: dotnet test YourWpfApp/YourWpfApp.csproj

      - name: Publish Application
        run: dotnet publish YourWpfApp/YourWpfApp.csproj -c Release -o ./publish

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: ./publish
